"""Tests for ctd_sampling.smoothing.

The golden values below were generated by running the original
``conv2P.m`` under ``octave-cli``, e.g.::

    octave-cli --eval "
    x = [1;2;3;4;5;6;7;8;9;10];
    k5 = ones(5,1)/5; k10 = ones(10,1)/10;
    disp(conv2P(x, k5)'); disp(conv2P(x, k10)')
    x2 = [NaN;NaN;1;2;NaN;4;5;6;NaN;NaN];
    disp(conv2P(x2, k5)')
    "
"""

import numpy as np

from ctd_sampling.smoothing import nan_smooth


def test_matches_octave_conv2p_odd_kernel() -> None:
    """An odd-length boxcar kernel should match conv2P.m's mirror-padded convolution."""
    x = np.arange(1, 11, dtype=float)
    kernel = np.ones(5) / 5

    result = nan_smooth(x, kernel)

    np.testing.assert_allclose(result, [1.8, 2.2, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 8.8, 9.2])


def test_matches_octave_conv2p_even_kernel() -> None:
    """An even-length kernel should match conv2P.m's half-sample-recentered convolution."""
    x = np.arange(1, 11, dtype=float)
    kernel = np.ones(10) / 10

    result = nan_smooth(x, kernel)

    np.testing.assert_allclose(
        result,
        [3.05, 3.25, 3.65, 4.25, 5.05, 5.95, 6.75, 7.35, 7.75, 7.95],
    )


def test_matches_octave_conv2p_with_nan_gaps() -> None:
    """Interior NaN gaps and leading/trailing NaN runs should match conv2P.m."""
    x = np.array([np.nan, np.nan, 1, 2, np.nan, 4, 5, 6, np.nan, np.nan])
    kernel = np.ones(5) / 5

    result = nan_smooth(x, kernel)

    expected = [np.nan, np.nan, 1.8, 2.2, np.nan, 4.0, 4.8, 5.2, np.nan, np.nan]
    np.testing.assert_allclose(result, expected)


def test_all_nan_input_returned_unchanged() -> None:
    """An all-NaN input has no finite span to smooth and should pass through unchanged."""
    x = np.full(6, np.nan)

    result = nan_smooth(x, np.ones(3) / 3)

    assert np.all(np.isnan(result))


def test_single_finite_point_left_unsmoothed() -> None:
    """A single finite point has nothing to interpolate through and should pass through as-is."""
    x = np.array([np.nan, np.nan, 5.0, np.nan, np.nan])

    result = nan_smooth(x, np.ones(3) / 3)

    np.testing.assert_allclose(result, x)
