"""Tests for ctd_sampling.binning.

The golden values below were generated by running the original
``bindata_AS.m`` under ``octave-cli``, e.g.::

    octave-cli --eval "
    x = [1 2 3 4 6 9 10 10.4];
    y = [1 2 3 4 6 9 NaN 10.4];
    gx = [0 2 4 6 8 10]';
    [b,n,s] = bindata_AS(x,y,gx);
    disp(b'); disp(n')
    "
"""

import numpy as np
import pytest

from ctd_sampling.binning import bin_average


def test_matches_octave_bindata_as_basic() -> None:
    """Bin averages should match bindata_AS.m's output on a small mixed-occupancy case."""
    x = np.array([1, 2, 3, 4, 6, 9, 10, 10.4])
    y = np.array([1, 2, 3, 4, 6, 9, np.nan, 10.4])
    bin_centers = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])

    mean, count = bin_average(x, y, bin_centers)

    np.testing.assert_allclose(mean, [1.0, 2.5, 4.0, 6.0, 9.0, 10.4])
    np.testing.assert_allclose(count, [1, 2, 1, 1, 1, 1])


def test_matches_octave_bindata_as_empty_bins() -> None:
    """Empty bins should be NaN in both mean and count, matching bindata_AS.m."""
    x = np.array([1.0, 2.0, 9.0])
    y = np.array([1.0, 2.0, 9.0])
    bin_centers = np.array([0.0, 2.0, 4.0, 6.0, 8.0, 10.0])

    mean, count = bin_average(x, y, bin_centers)

    np.testing.assert_allclose(mean, [1.0, 2.0, np.nan, np.nan, 9.0, np.nan])
    np.testing.assert_allclose(count, [1, 1, np.nan, np.nan, 1, np.nan])


def test_all_nan_input_returns_all_nan() -> None:
    """All-NaN y input should short-circuit to all-NaN mean and count."""
    x = np.array([1.0, 2.0, 3.0])
    y = np.full(3, np.nan)
    bin_centers = np.array([0.0, 2.0, 4.0])

    mean, count = bin_average(x, y, bin_centers)

    assert np.all(np.isnan(mean))
    assert np.all(np.isnan(count))


def test_rejects_too_few_bin_centers() -> None:
    """A single bin center has no well-defined bin width and should raise."""
    with pytest.raises(ValueError, match="at least 2"):
        bin_average(np.array([1.0]), np.array([1.0]), np.array([0.0]))
