## Copyright (c) 2023, 2025, 2026  University of Washington.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are met:
##
## 1. Redistributions of source code must retain the above copyright notice, this
##    list of conditions and the following disclaimer.
##
## 2. Redistributions in binary form must reproduce the above copyright notice,
##    this list of conditions and the following disclaimer in the documentation
##    and/or other materials provided with the distribution.
##
## 3. Neither the name of the University of Washington nor the names of its
##    contributors may be used to endorse or promote products derived from this
##    software without specific prior written permission.
##
## THIS SOFTWARE IS PROVIDED BY THE UNIVERSITY OF WASHINGTON AND CONTRIBUTORS “AS
## IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
## IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
## DISCLAIMED. IN NO EVENT SHALL THE UNIVERSITY OF WASHINGTON OR CONTRIBUTORS BE
## LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
## CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
## GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
## LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
## OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

###
# NOTE: This file is part of basestation3 source and should not be modified.  This same
# named file is searched for in the following locations:
#   <basestation_dir>/config
#   <basestation_dir>/etc
#   <--group_etc dir>
#   <gliders mission dir>
# New plots or updates to any of the plots listed below need to be the complete plot definition.
##
---
fet:
  instrument: fet
  layout:
    xaxis2_title: nano amps
    xaxis_title: Volts
  vars:
    Ib:
      color_down: olive
      color_up: darkolivegreen
      hoverfmt: .4f
      units: uI
      visible: legendonly
      xaxis: x2
    Ik:
      color_down: Blue
      color_up: DarkBlue
      hoverfmt: .4f
      units: uI
      visible: legendonly
      xaxis: x2
    Vk:
      color_down: orange
      color_up: darkgoldenrod
      hoverfmt: .4f
      units: V
      visible: legendonly
      xaxis: x1
    Vkstd:
      color_down: Green
      color_up: DarkGreen
      hoverfmt: .3g
      units: V
      visible: legendonly
      xaxis: x1
    Vrse:
      color_down: Red
      color_up: Magenta
      hoverfmt: .4f
      units: V
      xaxis: x1
    Vrsestd:
      color_down: Cyan
      color_up: DarkCyan
      hoverfmt: .3g
      units: V
      visible: legendonly
      xaxis: x1
    biasBatt:
      color_down: LightGrey
      color_up: DarkGrey
      hoverfmt: .2f
      units: V
      visible: legendonly
      xaxis: x1
microriderg:
  instrument: microriderg
  layout:
    xaxis_title: ''
  vars:
    e_1:
      color_down: Green
      color_up: DarkGreen
      hoverfmt: .4f
      units: ''
      xaxis: x1
    e_2:
      color_down: Red
      color_up: Magenta
      hoverfmt: .4f
      units: ''
      xaxis: x1
suna:
  instrument: suna
  layout:
    xaxis2_title: Temperature (C)
    xaxis_title: mmol m<sup>-3</sup>
  vars:
    nitrate:
      color_down: LightGreen
      color_up: DarkGreen
      hoverfmt: .4f
      units: mmol m-3
      xaxis: x1
#    temperature:
#      color_down: Red
#      color_up: Magenta
#      hoverfmt: .4f
#      units: C
#      xaxis: x2
