% Establishes glider calibration constants.

% This file is an example as well as documentation.
% Lines prefixed with %PARAM are parameters, the default value as the right hand side - remove "%PARAM " to enable
% Note - this file MUST be changed apprpriately for your vehicle and mission

% REQUIRED
id_str = '554';

% REQUIRED
mission_title ='Shilshole 30 Sep 2026';

% REQUIRED
mass = 55.432 ; % (kg) scale weight

% Optional
%PARAM mass_comp = 0;

% Correction factor to apply to truck depth to compensate for data with incorrect pressure slope
% Only change this if you are sure your dataset has this issue
%PARAM depth_slope_correction = 1.0;

% NOTE:
% FlightModel will supply
%
%  volmax, vbdbias, hd_a, hd_b, hd_c, hd_s, rho0, abs_compress, therm_expan, temp_ref
%
% ignoring any settings here and issue a warning, unless
% --skip_flight_model is set, in which case processing will use these
% variables. To suppress warnings about these variables, insert FM_ignore anywhere in a comment on the same
% line as the variable
%

%
% Parms affecting basestation processing
%
% The allowable horizontal position error (HPE) in GPS fixes.  GPS fixes with measured HPE values greater
% then this value are not usable in surface dift and/or depth averaged current calculations
%PARAM GPS_position_error = 100;
%


%
% Legato CTD
%

% Required
sg_ct_type = 4;  % Indicates a legato CTD

calibcomm = 'Legato4 s/n 241429 calibration 30 March 2026';

% Required for Legato as logdev or on the truck
legato_sealevel = 10171.0; % Where this is sealevel presure setting.

% Set to 1 to use the Seaglider pressure sensor for CTD corrections
%PARAM legato_use_truck_pressure = 0;

% Set to 0 to disable the basestation conductivity pressure correction, in favor of the on in the instrument
% On board correction is applied when X2, X3 and X4 are non-zero (see metadata capture from a selftest)
% See RBR document "0013279revA Conductivity pressure correction for RBRlegato3 with RBR#0007155 top.pdf"
%PARAM legato_cond_press_correction = 1;

% Misc legato settings

% ignore any legato columns from the truck
%PARAM ignore_truck_legato = 1; 

%
% RBR tridente
%

% The correct form of this parameter is generated by running
%    /opt/basestation/bin/python /usr/local/basestation3/tools/GetTridenteChannels.py <selftest>
% where selftest is a selftest capture file that contains the tridente meta data.

%This parameter is only used to annotate tridente plots
%PARAM calibcomm_tridentebb700bb470chla470='RBRtridente serialnum:238008 backscatter_00:2025-03-12T13:01:47Z backscatter_01:2025-03-12T13:06:10Z chlorophyll_00:2025-03-11T12:40:47Z';

%
% RBR codaTODO
%

% The correct form of the parameters below are generated by running
%    /opt/basestation/bin/python /usr/local/basestation3/tools/GetCodaMeta.py <selftest>
% where selftest is a selftest capture file that contains the CODA meta data.

% This parameter is only used to annotate coda plots.
%PARAM calibcomm_codaTODO='RBRcoda serialnum:237923 temp15:2025-03-15T13:54:16Z doxy24:2025-03-20T11:35:41Z opt_05:2025-03-03T14:18:09Z';

% This parameter is used to calculate an additional compensater O2 vector (in addtion to the one reported by the instrument) using corrected salinity from the CTD.  See /usr/local/basesation3/Sensors/coda_ext.py for further details.
%PARAM codaTODO_c0=32.000000e-006;

%
% Aanderaa Optode
%

% The parameters needed to correct the aanderaa optode output can be obtained by running
%    /opt/basestation/bin/python /usr/local/basestation3/tools/GetOptodeConstants.py <selftest>
% where selftest is a selftest capture file that contains the aanderaa optode meta data.

%PARAM calibcomm_optode = ''Optode 4831 SN: 940  Foil ID: 1824M calibrated 03-12-2020'';

%PARAM optode_PhaseCoef0 = -2.734;
%PARAM optode_PhaseCoef1 = 1;
%PARAM optode_PhaseCoef2 = 0;
%PARAM optode_PhaseCoef3 = 0;
%PARAM optode_ConcCoef0 = 0;
%PARAM optode_ConcCoef1 = 1;
%PARAM optode_FoilCoefA0 = -2.67928e-06;
%PARAM optode_FoilCoefA1 = -7.4836e-06;
%PARAM optode_FoilCoefA2 = 0.00196001;
%PARAM optode_FoilCoefA3 = -0.207285;
%PARAM optode_FoilCoefA4 = 0.000601246;
%PARAM optode_FoilCoefA5 = -6.60427e-07;
%PARAM optode_FoilCoefA6 = 11.1802;
%PARAM optode_FoilCoefA7 = -0.0514806;
%PARAM optode_FoilCoefA8 = 6.8985e-05;
%PARAM optode_FoilCoefA9 = 8.46501e-07;
%PARAM optode_FoilCoefA10 = -314.351;
%PARAM optode_FoilCoefA11 = 2.05112;
%PARAM optode_FoilCoefA12 = -0.00298703;
%PARAM optode_FoilCoefA13 = -4.44977e-06;
%PARAM optode_FoilCoefB0 = -1.86135e-06;
%PARAM optode_FoilCoefB1 = 3814.9;
%PARAM optode_FoilCoefB2 = -32.2281;
%PARAM optode_FoilCoefB3 = -0.1678;
%PARAM optode_FoilCoefB4 = 0.0189482;
%PARAM optode_FoilCoefB5 = -0.000690143;
%PARAM optode_FoilCoefB6 = 1.04269e-05;
%PARAM optode_FoilCoefB7 = 0;
%PARAM optode_FoilCoefB8 = 0;
%PARAM optode_FoilCoefB9 = 0;
%PARAM optode_FoilCoefB10 = 0;
%PARAM optode_FoilCoefB11 = 0;
%PARAM optode_FoilCoefB12 = 0;
%PARAM optode_FoilCoefB13 = 0;
%PARAM optode_SVU_enabled = 1;
%PARAM optode_SVUCoef0 = 0.00276388;
%PARAM optode_SVUCoef1 = 0.00011389;
%PARAM optode_SVUCoef2 = 2.47865e-06;
%PARAM optode_SVUCoef3 = 166.347;
%PARAM optode_SVUCoef4 = -0.263223;
%PARAM optode_SVUCoef5 = -37.8607;
%PARAM optode_SVUCoef6 = 3.37836;

%
% Johnson, Plant, Riser, Gilbert. 'Air oxygen calibration of oxygen optodes on a profiling float array'
% submitted, Journal of Atmospheric and Oceanic Technology 2015
% The optode apparently drifts from its calibration when exposed to air but then stops drifting in (sea)water.
% Investigation shows this is captured by a gain rather
% than additive drift, that is, the drift is proportional to the O2 signal. Johnson et al. compute the gain
% by comparing the output of the sensor in air with the expected
% O2 concentration given temperature and pressure.
%
% These parameter are not supplied by the above tool
%PARAM optode_st_temp = 10.723; % From selftest capture
%PARAM optode_st_calphase = 30.826; % From selftest capture
%PARAM optode_st_slp = 1008.3; % From local observation

