on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create the Mattermost message
        run: |
          jq '{
            text: (
              " **\(.repository.name)**  \n _\(.pusher.name)_   \n" +
              ((.commits // []) | map("- " + .message) | join("\n"))
            )
          }' "$GITHUB_EVENT_PATH" > mattermost.json

      - name: Send the Mattermost message
        uses: mattermost/action-mattermost-notify@1.1.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
